# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      echo 'start script'
      cd backend
      # Create & Activate virtual environment
      #python -m venv env
      #source env/bin/activate
      # Install dependencies
      pip install -r requirements.txt
      # Database setup
      python manage.py db init &
      python manage.py db migrate & 
      python manage.py db upgrade
      # Run backend server
      python manage.py runserver

      cd ../frontend
      # install dependencies
      npm install

      # serve with hot reload at localhost:8080
      npm run dev

      # build for production with minification
      npm run build

      # build for production and view the bundle analyzer report
      npm run build --report

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
